# Generated by Django 5.0.6 on 2024-06-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='notes',
        ),
    ]
