# Generated by Django 5.0.6 on 2024-06-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
