# Generated by Django 5.0.6 on 2024-06-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_note_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loved', models.TextField(max_length=100)),
                ('liked', models.TextField(max_length=100)),
                ('neutral', models.TextField(max_length=100)),
                ('disliked', models.TextField(max_length=100)),
                ('hated', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('games', models.ManyToManyField(to='main_app.game')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='bachelors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.bachelor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bachelorette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loved', models.TextField(max_length=100)),
                ('liked', models.TextField(max_length=100)),
                ('neutral', models.TextField(max_length=100)),
                ('disliked', models.TextField(max_length=100)),
                ('hated', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('games', models.ManyToManyField(to='main_app.game')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='bachelorettes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.bachelorette'),
            preserve_default=False,
        ),
    ]
