# Generated by Django 5.0.6 on 2024-06-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_bachelor_note_bachelors_bachelorette_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=3500),
        ),
    ]
