# Generated by Django 5.0.6 on 2024-06-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_note_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='bachelors',
            new_name='bachelor',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='bachelorettes',
            new_name='bachelorette',
        ),
    ]
